version: '3.8'

services:
  train:
    build: .
    volumes:
      - .:/app
      - ./dataset:/app/dataset
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./dataset:/app/dataset
    command: uvicorn scripts.5_deploy_model:app --host 0.0.0.0 --port 8000
    environment:
      - MODEL_PATH=/app/dataset/models/latest_model.h5

  collect:
    build: .
    volumes:
      - ./dataset:/app/dataset
    command: python3 scripts/1_collect_data.py

  redis:
    image: redis:latest
    ports:
      - "6379:6379"